name: Add to Project

on:
  issues:
    types:
      - opened
      - transferred

permissions:
  contents: read

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@31b3f3ccdc584546fc445612dec3f38ff5edb41c # v0.5.0
        with:
          project-url: https://github.com/orgs/camunda/projects/33
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}