# Copy files to the gh-pages branch to have clean and shorter links.
# Example: https://helm.camunda.io/camunda-platform/values/values-latest.yaml
name: "Chart - Public Files"

on:
  push:
    branches:
    - main
    paths:
    - '.github/workflows/chart-public-files.yaml'
    - 'charts/camunda-platform*/values*.yaml'
    - 'scripts/templates/version-matrix/*'
    - 'version-matrix/**'
  workflow_dispatch: { }

permissions:
  contents: read

jobs:
  copy-files:
    name: Copy chart public files
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          ref: gh-pages
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          path: main
      - name: Copy files
        run: |
          #
          # Values files.
          mkdir -p camunda-platform/values

          # Latest version.
          cp -a main/charts/camunda-platform-latest/values-latest.yaml camunda-platform/values/values-latest.yaml

          # Previous versions.
          find main/charts -name "camunda-platform-*" | while read chart_id; do
              camunda_version="$(echo ${chart_id} | cut -d '-' -f 3)";
              echo "cp -a main/${chart_id}/values-latest.yaml camunda-platform/values/values-v${camunda_version}.yaml";
          done

          #
          # Version matrix.
          mkdir -p camunda-platform/version-matrix
          cp -a main/version-matrix/* camunda-platform/version-matrix/

          #
          # Post run.            
          rm -rf main
          find .
      - uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
        with:
          message: "chore: update camunda-platform public files"
