name: "Chart - Release - PR"

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

env:
  RELEASE_PLEASE_CONFIG_FILE: .github/config/release-please/release-please-config.json
  RELEASE_PLEASE_MANIFEST_FILE: .github/config/release-please/.release-please-manifest.json

jobs:
  release-please:
    name: Run Release Please
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2
        id: generate-github-token
        with:
          app_id: ${{ secrets.GH_APP_ID_DISTRO_CI }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY_DISTRO_CI }}
      - uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4
        with:
          token: '${{ steps.generate-github-token.outputs.token }}'
          # Config docs: https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md
          config-file: "${{ env.RELEASE_PLEASE_CONFIG_FILE }}"
          manifest-file: "${{ env.RELEASE_PLEASE_MANIFEST_FILE }}"
