# Copy values files to the gh-pages branch to have clean and shorter links.
# Example: https://helm.camunda.io/camunda-platform/values/values-latest.yaml
name: "Chart - Values Files"

on:
  push:
    branches:
    - main
    paths:
    - 'charts/camunda-platform/values/*.yaml'
  workflow_dispatch: { }

permissions:
  contents: write

jobs:
  copy-values-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          ref: gh-pages
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          path: main
      - name: Copy the values files
        run: |
          mkdir -p camunda-platform/values
          cp -a main/charts/camunda-platform/values/*.yaml camunda-platform/values/
          rm -rf main
          find .
      - uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
        with:
          message: "chore: update camunda-platform values files"
