name: "Chart - Validate"

on:
  # Allow to run the workflow from GitHub UI and other workflows.
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/**'
      - '.tool-versions'
      - 'charts/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: asdf-vm/actions/install@05e0d2ed97b598bfce82fd30daf324ae0c4570e6 # v3
      - name: Add helm repos
        run: |
          make helm.repos-add
      - name: Get Helm dependency
        run: |
          make helm.dependency-update
      - name: Run Helm lint 
        run: |
          helm lint --strict charts/*
      - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4
        with:
          python-version: 3.7
      - name: Set up chart-testing
        uses: helm/chart-testing-action@e6669bcd63d7cb57cb4380c33043eebe5d111992 # v2.6.1
      - name: Don't check version increment if there is no release label
        if: ${{ ! contains(github.event.*.labels.*.name, 'release') }}
        run: |
          echo "check-version-increment: false" >> .github/config/chart-testing.yaml
      - name: Run chart testing and lint
      #check to see if this works:
        run: ct lint --config .github/config/chart-testing.yaml
      - name: Lint YAML Files
        run: |
          yamllint -c .github/config/yamllint.yaml ./charts/camunda-platform/test/unit
