# Mimic postUpgradeTasks which is only available for self-hosted Renovate instances.
# https://docs.renovatebot.com/configuration-options/#postupgradetasks
name: Renovate - Post Upgrade Tasks

on:
  push:
    branches:
    - 'renovate/*'
    paths:
    - 'charts/camunda-platform/values.yaml'
    - 'charts/camunda-platform/templates/**'
    - 'charts/camunda-platform/charts/**'

jobs:
  run:
    name: Update golden files
    runs-on: ubuntu-latest
    steps:
    - name: Generate GitHub token
      uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2
      id: generate-github-token
      with:
        app_id: ${{ secrets.GH_APP_ID }}
        private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      with:
        token: '${{ steps.generate-github-token.outputs.token }}'
    - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
      with:
        go-version-file: go.mod
        cache: false
    - uses: asdf-vm/actions/setup@05e0d2ed97b598bfce82fd30daf324ae0c4570e6 # v3
    - uses: actions/cache@e12d46a63a90f2fae62d114769bbf2a179198b5c # v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Update golden files
      run: make go.update-golden-only
    - uses: EndBug/add-and-commit@1bad3abcf0d6ec49a5857d124b0bfb52dc7bb081 # v9.1.3
      with:
        author_name: "renovate[bot]"
        author_email: "29139614+renovate[bot]@users.noreply.github.com"
        message: "chore(deps): post upgrade tasks - update golden files"
