name: Repo - Pull Request Conventions

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  lint-format:
    runs-on: ubuntu-latest

    steps:
      - uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            refactor
            test
            docs
            style
            build
            ci
            chore
            chore(deps)
            chore(release)
          # Configure additional validation for the subject based on a regex.
          # Ensures the subject doesn't start with an uppercase character.
          subjectPattern: ^(?![A-Z]).+$
          # Ignore release PR since it's different and already automated.
          ignoreLabels: |
            release/pr
          # When using "Squash and merge" on a PR with only one commit, GitHub
          # will suggest using that commit message instead of the PR title for the
          # merge commit, and it's easy to commit this by mistake. Enable this option
          # to also validate the commit message for one commit PRs.
          validateSingleCommit: true
