# TODO: Move the PR trigger to its own workflow and use this workflow as template only.
name: "Test - Integration - Main"

on:
  pull_request_target:
    paths:
    - '.github/workflows/test-integration-main.yaml'
    - '.tool-versions'
    - 'charts/**'
    types: [opened, closed, reopened, synchronize]
  workflow_call:
    inputs:
      persistent:
        description: |
          Keep test deployment after the workflow is done.
          NOTE: All persistent deployments will be deleted frequently to save costs!
        required: false
        default: false
        type: boolean
      platforms:
        default: gke
        type: string
      identifier:
        description: The unique identifier of used in the deployment hostname.
        required: true
        type: string
      extra-values:
        description: Pass extra values to the Helm chart.
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || inputs.identifier || github.ref }}
  cancel-in-progress: true

env:
  JESSE_SECRET: ${{ secrets.JESSE_SECRET }}

jobs:
  jessejob:
    runs-on: ubuntu-latest
    steps:
    - name: jesse task
      run: echo hello jesse. Heres your message: $JESSE_SECRET

