name: "Test - Unit"

on:
  push:
    branches:
    - main
    paths:
    - '.github/**'
    - '.tool-versions'
    - 'charts/**'
    - 'go.*'
  pull_request:
    paths:
    - '.github/**'
    - '.tool-versions'
    - 'charts/**'
    - 'go.*'
  workflow_dispatch: { }

jobs:
  jessejob:
    runs-on: ubuntu-latest
    steps:
    - name: jesse task
      run: echo hello
