# Basic test for older Camunda 8 Helm charts.
name: "Test - Regression"

on:
  push:
    paths:
    - 'charts/camunda-platform/values/values-v8*.yaml'
  pull_request:
    paths:
    - 'charts/camunda-platform/values/values-v8*.yaml'
  workflow_dispatch: { }

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


permissions:
  contents: read

jobs:
  jessejob:
    runs-on: ubuntu-latest
    steps:
    - name: jesse task
      run: echo hello
